version: '3'
services:
  executer-mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017-27019:27017-27019
    env_file:
      - executer-mongo.env
    networks:
      - nesjs-network
  executer:
    image: executor:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - executer-mongo
    networks:
      - nesjs-network
    ports:
      - 3000:3000
networks:
    nesjs-network:
      driver: bridge
